### ISSUE TITLE
Post isn't showing up in my blog :(

### ISSUE THREAD

**Issue by ndphillips** [privefl/prettyjekyll#4]
After running `prettyjekyll::FormatPost()` I just pushed a new post to my blog here (https://github.com/ndphillips/blog/tree/gh-pages/_posts) titled "FFTreesAugust" but it's not showing up in my blog (https://ndphillips.github.io/blog/) like my prior post. 

Any advice?

**Comment by privefl** [comment]
Two things:
- are you using the latest version of this package? I made some changes recently.
- also, I think you should modify your date to be `August 10, 2017` instead of `August 10 2017`, or using  option `date.format = "%B %d %Y"`.

**Comment by ndphillips** [comment]
Thanks for the fast response! I think the problem was in one or more of the characters I was using in my title (e.g.; --). Now that I've cleaned the title up, it's working great, thanks!

One issue though: The <iframe> in the document isn't showing up now in the final output

Output (towards the bottom): https://ndphillips.github.io/blog/simplicity-matters-3-updates-to-the-fftrees-universe/

Any ideas how to fix this?

**Comment by privefl** [comment]
Seems likes the `>` and `<` are converted in character code. 

I think this is because you should use the format of RMarkdown from this package (Jekyll Pretty Document from {prettyjekyll}).

I don't think this package works with a `github_document`.

**Comment by asb1234** [comment]
My settings say my blog is published and all seems well but when I publish a post it doesn’t show up

**Comment by privefl** [comment]
Can you provide reference to the Rmd/md you're talking about?

**Comment by asb1234** [comment]
Jekyll

**Comment by privefl** [comment]
Did you find the root of the problem?
