### ISSUE TITLE
dependency 'glue' is not available for package 'prettyjekyll'

### ISSUE THREAD

**Issue by Maouriyan** [privefl/prettyjekyll#5]
I get this error when I try to install this package 
> devtools::install_github("privefl/prettyjekyll")
Downloading GitHub repo privefl/prettyjekyll@master
from URL https://api.github.com/repos/privefl/prettyjekyll/zipball/master
Installing prettyjekyll
"C:/PROGRA~1/MIE74D~1/RCLIEN~1/R_SERVER/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/nibsz/AppData/Local/Temp/Rtmp6pIucy/devtools31e42ccf49a6/privefl-prettyjekyll-5e2a0fb"  \
  --library="C:/Users/nibsz/Documents/r/win-library/3.3" --install-tests 

ERROR: dependency 'glue' is not available for package 'prettyjekyll'
* removing 'C:/Users/nibsz/Documents/r/win-library/3.3/prettyjekyll'
Error: Command failed (1)

**Comment by privefl** [comment]
It seems that you have R in version 3.3.x, which is a pretty old version which may not have any binaries for package {glue}.
You have at least two solutions:
- install package {glue} from the GitHub sources: `devtools::install_github("tidyverse/glue")`
- update R (you should really do that)
