### ISSUE TITLE
plots not showing up in blog

### ISSUE THREAD

**Issue by SwampThingPaul** [privefl/prettyjekyll#7]
In my .rmd file I have several plots being generated (i.e. plot(), etc). It seems that when the files are rendered and posted to GitHub the file designation gets all jumbled. But this only happens for plot generated within the Rmd file. Regular images that are stored in the  "../images/.." folder are fine. Below is a path that the blog inserts to reference the post rendered image. It seems like it is inserting the {{site.url}}{{site.baseurl}} twice? Is there something somewhere I need to edit to fix this? Hope I was able to articulate the issue

"https://swampthingpaul.github.io/blog/_knitr/https://swampthingpaul.github.io/blog/knitr_files/2019-01-16-FCELTER_files/figure-html/STAarea_plot-1.png"

Here is the actual post. 
https://swampthingpaul.github.io/blog/external-drivers-that-can-influence-internal-processes/

**Comment by privefl** [comment]
This might be a bug.
Where can I find the corresponding Rmd?

**Comment by SwampThingPaul** [comment]
Hi @privefl, thanks for the quick reply. The .rmd file is located at this [link](https://github.com/SwampThingPaul/blog/blob/cd7b42c81901c566c9cf37d1556acafda653bad5/_knitr/2019-01-16-FCELTER.Rmd). The entire blog repo is [here](https://github.com/SwampThingPaul/blog).

**Comment by privefl** [comment]
I'm able to reproduce this issue.
I'll try to investigate.

**Comment by privefl** [comment]
Yet, something is different. Are you using `"_knitr"` as `tmp.dir`?

**Comment by SwampThingPaul** [comment]
I am using the `../_kntir` directory to keep the `.rmd` file for each post then using `prettyjekyll::FormatPost("_knitr/post.Rmd")` to complie the md file. I do call in data from other directories but do everything from `../_kntir`.

**Comment by SwampThingPaul** [comment]
I also edited the [Test Post](https://swampthingpaul.github.io/blog/test-post/) to include a simple plot `plot(rnorm(100))` and I run into the same issue, rmd file is [here](https://github.com/SwampThingPaul/blog/blob/dd4feeb4fcd2f42675b73b24cd8ef3e21da24fc3/_knitr/knitr-minimal.Rmd). I am no package/code expert but it seems like maybe something in the [FormatPost](https://github.com/privefl/prettyjekyll/blob/82883f9fc28e692fa6e24337d98c77e385a28058/R/FormatPost.R) function around lines 61 - 81 might be the issue? ...but then again it might be something completely different. Just trying to help.

I also tried to update the `prettyjekyll` package and get the notification that I have the most recent package.

**Comment by privefl** [comment]
Thanks for this minimal example.
I will work on this tomorrow. Not sure I'll have time today.

**Comment by SwampThingPaul** [comment]
No problem. Just trying to help :wink:

**Comment by privefl** [comment]
Could you please try again with the version I just pushed?

**Comment by SwampThingPaul** [comment]
I just re-installed the`prettyjekyll` package using `devtools::install_github("privefl/prettyjekyll")`. It updated without a hitch. But the problem still persists. 

I took a quick look at `.md` file of the minial example shared above generated from using the `FormatPost()` function and noticed that for plots generated in the rmd it adds an extra `{{site.url}}{{site.basurl}}\_knitr\` in the img src code. The `.md` file is [here](https://github.com/SwampThingPaul/blog/blob/5ce75b43a7a333e6f46d5836a9d3d498e81de8a9/_posts/2018-12-15-test-post.md). 

If I go in by hand and remove `{{site.url}}{{site.basurl}}\_knitr\` the image and associated r-chunk works.

I am no expert but it seems like an `if( ){ }else{ }` statement indicating if the figure is from `.../_knitr/...` do one thing or if the figure is from `.../image/...` do another. But I am not sure if 1) it will work or 2) where to do that 3) exactly how to do that...like I said no-expert. 

Hope this helped with debugging.

**Comment by privefl** [comment]
It appears that `normalizePath(path, mustWork = FALSE)` has a different behaviour between Linux and Windows..
Could you try again now?

**Comment by SwampThingPaul** [comment]
You sir are a wizard!! Looks like it is fixed. Both minimal example and larger post (both linked above) are working.

**Comment by privefl** [comment]
Honestly, I should have run tests on Windows as well.

Thanks for reporting
